name = "r2-upload-relay"
main = "r2-upload.js"
compatibility_date = "2026-05-31"
compatibility_flags = [ "nodejs_compat" ]

[observability]
enabled = true

  [observability.logs]
  head_sampling_rate = 1

  [observability.traces]
  enabled = true
  head_sampling_rate = 0.01

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "claude"
